USE DML_EST_CASO_I

DELETE FROM FORNECEDORES WHERE FORNEC_COD = 1;

UPDATE FORNECEDORES 
SET FORNEC_NOME = 'Fornecedor A Modificado' 
WHERE FORNEC_COD = 2;
UPDATE FORNECEDORES 
SET FORNEC_TELEFONE = '1234-5678' 
WHERE FORNEC_COD = 3;

INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES (1, 'Fornecedor 1', 'Rua A', 100, 'Bairro 1', 'Cidade 1', 'Estado 1', 'Brasil', '12345-678', '9999-9999', 'Contato 1');
INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES (2, 'Fornecedor 2', 'Rua B', 200, 'Bairro 2', 'Cidade 2', 'Estado 2', 'Brasil', '23456-789', '9888-8888', 'Contato 2');
INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES (3, 'Fornecedor 3', 'Rua C', 300, 'Bairro 3', 'Cidade 3', 'Estado 3', 'Brasil', '34567-890', '9777-7777', 'Contato 3');
INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES (4, 'Fornecedor 4', 'Rua D', 400, 'Bairro 4', 'Cidade 4', 'Estado 4', 'Brasil', '45678-901', '9666-6666', 'Contato 4');
INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES (5, 'Fornecedor 5', 'Rua E', 500, 'Bairro 5', 'Cidade 5', 'Estado 5', 'Brasil', '56789-012', '9555-5555', 'Contato 5');


DELETE FROM FILIAIS WHERE FILIAL_COD = 1;

UPDATE FILIAIS 
SET FILIAL_NOME = 'Filial A Modificada' 
WHERE FILIAL_COD = 2;
UPDATE FILIAIS 
SET FILIAL_CIDADE = 'Cidade Nova' 
WHERE FILIAL_COD = 3;

INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES (1, 'Filial 1', 'Rua F', 1000, 'Bairro F', 'Cidade F', 'Estado F', 'Brasil', '67890-123', 'Capacidade 1');
INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES (2, 'Filial 2', 'Rua G', 1100, 'Bairro G', 'Cidade G', 'Estado G', 'Brasil', '78901-234', 'Capacidade 2');
INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES (3, 'Filial 3', 'Rua H', 1200, 'Bairro H', 'Cidade H', 'Estado H', 'Brasil', '89012-345', 'Capacidade 3');
INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES (4, 'Filial 4', 'Rua I', 1300, 'Bairro I', 'Cidade I', 'Estado I', 'Brasil', '90123-456', 'Capacidade 4');
INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES (5, 'Filial 5', 'Rua J', 1400, 'Bairro J', 'Cidade J', 'Estado J', 'Brasil', '01234-567', 'Capacidade 5');


DELETE FROM PRODUTOS WHERE PROD_COD = 1;

UPDATE PRODUTOS 
SET PROD_NOME = 'Produto A Modificado' 
WHERE PROD_COD = 2;
UPDATE PRODUTOS 
SET PROD_QUANT = 1500 
WHERE PROD_COD = 3;

INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (1, 'Produto 1', 'Descrição do Produto 1', 'Especificação 1', 1000, 20.50, 'un', 50);
INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (2, 'Produto 2', 'Descrição do Produto 2', 'Especificação 2', 2000, 30.75, 'kg', 100);
INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (3, 'Produto 3', 'Descrição do Produto 3', 'Especificação 3', 3000, 10.20, 'caixa', 150);
INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (4, 'Produto 4', 'Descrição do Produto 4', 'Especificação 4', 4000, 15.00, 'litro', 200);
INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES (5, 'Produto 5', 'Descrição do Produto 5', 'Especificação 5', 5000, 50.00, 'un', 250);


DELETE FROM PEDIDOS WHERE PED_CODIGO = 1;

UPDATE PEDIDOS 
SET PED_STATUS = 'CONCLUÍDO' 
WHERE PED_CODIGO = 2;
UPDATE PEDIDOS 
SET PED_PREVISAO = '2024-12-31' 
WHERE PED_CODIGO = 3;

INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (1, '2024-11-01', '12:00:00', '2024-11-10', 'PENDENTE', 1);
INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (2, '2024-11-02', '14:30:00', '2024-11-15', 'EM ESPERA', 2);
INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (3, '2024-11-03', '16:45:00', '2024-11-20', 'PENDENTE', 3);
INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (4, '2024-11-04', '09:00:00', '2024-11-25', 'CONCLUÍDO', 4);
INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES (5, '2024-11-05', '11:15:00', '2024-11-30', 'EM ESPERA', 5);


DELETE FROM RECEBIMENTOS WHERE RECEB_PEDIDOS = 1;

UPDATE RECEBIMENTOS 
SET RECEB_QUANT_PROD = 500 
WHERE RECEB_PEDIDOS = 2;
UPDATE RECEBIMENTOS 
SET RECEB_CONDICAO = 'Condição de pagamento alterada' 
WHERE RECEB_PEDIDOS = 3;

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-06', '10:00:00', 100, 'Pagamento à vista', 1);
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-07', '11:30:00', 200, 'Parcelado', 2);
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-08', '13:00:00', 300, 'Pagamento à vista', 3);
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-09', '15:00:00', 400, 'Parcelado', 4);
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES ('2024-11-10', '17:30:00', 500, 'Pagamento à vista', 5);


DELETE FROM PEDIDOS_PRODUTOS WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 1;

UPDATE PEDIDOS_PRODUTOS 
SET PDPR_QUANT = 200 
WHERE PDPR_PEDIDOS = 2 AND PDPR_PRODUTOS = 2;
UPDATE PEDIDOS_PRODUTOS 
SET PDPR_QUANT = 300 
WHERE PDPR_PEDIDOS = 3 AND PDPR_PRODUTOS = 3;

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (1, 1, 100);
INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (2, 2, 200);
INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (3, 3, 300);
INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (4, 4, 400);
INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES (5, 5, 500);


DELETE FROM FILIAIS_PRODUTOS WHERE FLPR_FILIAL = 1 AND FLPR_PRODUTOS = 1;

UPDATE FILIAIS_PRODUTOS 
SET FLPR_QUANT = 150 
WHERE FLPR_FILIAL = 2 AND FLPR_PRODUTOS = 2;
UPDATE FILIAIS_PRODUTOS 
SET FLPR_QUANT = 250 
WHERE FLPR_FILIAL = 3 AND FLPR_PRODUTOS = 3;

INSERT INTO FILIAIS_PRODUTOS (FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (1, 1, 100);
INSERT INTO FILIAIS_PRODUTOS (FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (2, 2, 200);
INSERT INTO FILIAIS_PRODUTOS (FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (3, 3, 300);
INSERT INTO FILIAIS_PRODUTOS (FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (4, 4, 400);
INSERT INTO FILIAIS_PRODUTOS (FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES (5, 5, 500);


DELETE FROM FORNECEDORES_PRODUTOS WHERE FRPR_FORNECEDOR = 1 AND FRPR_PRODUTOS = 1;

UPDATE FORNECEDORES_PRODUTOS 
SET FRPR_FORNECEDOR = 2 
WHERE FRPR_FORNECEDOR = 3 AND FRPR_PRODUTOS = 2;
UPDATE FORNECEDORES_PRODUTOS 
SET FRPR_PRODUTOS = 3 
WHERE FRPR_FORNECEDOR = 4 AND FRPR_PRODUTOS = 4;

INSERT INTO FORNECEDORES_PRODUTOS (FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (1, 1);
INSERT INTO FORNECEDORES_PRODUTOS (FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (2, 2);
INSERT INTO FORNECEDORES_PRODUTOS (FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (3, 3);
INSERT INTO FORNECEDORES_PRODUTOS (FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (4, 4);
INSERT INTO FORNECEDORES_PRODUTOS (FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES (5, 5);