DELETE FROM PASSAGEIROS WHERE PASS_CPF = 12345678901;

UPDATE PASSAGEIROS SET PASS_TELEFONE = '999999999' WHERE PASS_CPF = 12345678901;
UPDATE PASSAGEIROS SET PASS_CIDADE = 'São Paulo' WHERE PASS_CPF = 12345678901;
UPDATE PASSAGEIROS SET PASS_CIDADE = 'São Paulo' WHERE PASS_NOME = 'João Silva' AND PASS_CPF = 12345678901;

INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS)
VALUES (123451500, 'João Silva', '999999999', 'Rua X', 'Bairro Y', 123, 'São Paulo', 'Brasil');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS)
VALUES (987651201, 'Maria Oliveira', '988888888', 'Rua A', 'Bairro B', 456, 'Rio de Janeiro', 'Brasil');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS)
VALUES (112231302, 'Carlos Souza', '977777777', 'Rua C', 'Bairro D', 789, 'Belo Horizonte', 'Brasil');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS)
VALUES (223341403, 'Fernanda Lima', '966666666', 'Rua E', 'Bairro F', 101, 'Curitiba', 'Brasil');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS)
VALUES (345678901, 'Novo Passageiro', '999999999', 'Rua Exemplo', 'Bairro Exemplo', 123, 'Cidade Exemplo', 'Brasil');


DELETE FROM VOOS WHERE VOO_CODIGO = 101;

UPDATE VOOS SET PAIS_DESTINO = 'Espanha' WHERE VOO_CODIGO = 102;
UPDATE VOOS SET DATA_HORA_ORIGEM = '2024-12-10 15:00:00' WHERE VOO_CODIGO = 103;

INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO)
VALUES (123, '2024-12-01 08:00:00', '2024-12-01', '12:00:00', 'Argentina');
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO)
VALUES (102, '2024-12-02 09:30:00', '2024-12-02', '13:30:00', 'Espanha');
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO)
VALUES (103, '2024-12-03 10:45:00', '2024-12-03', '14:45:00', 'França');
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO)
VALUES (104, '2024-12-04 11:00:00', '2024-12-04', '15:00:00', 'Alemanha');
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO)
VALUES (105, '2024-12-05 12:15:00', '2024-12-05', '16:15:00', 'Portugal');


DELETE FROM AEROPORTO WHERE AEROPORTO_COD = 1;

UPDATE AEROPORTO SET AEROPORTO_LOCAL = 'Aeroporto Internacional de São Paulo' WHERE AEROPORTO_COD = 2;
UPDATE AEROPORTO SET AEROPORTO_PAIS = 'Brasil' WHERE AEROPORTO_COD = 3;

INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE)
VALUES (1, 'Aeroporto de Guarulhos', 'Aeroporto Internacional', 'Brasil', -46.5250, -23.4280);
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE)
VALUES (2, 'Aeroporto Santos Dumont', 'Aeroporto Nacional', 'Brasil', -43.1768, -22.9104);
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE)
VALUES (3, 'Aeroporto de Congonhas', 'Aeroporto Regional', 'Brasil', -46.6333, -23.6269);
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE)
VALUES (4, 'Aeroporto Internacional de Brasília', 'Aeroporto Internacional', 'Brasil', -47.9292, -15.7801);
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE)
VALUES (5, 'Aeroporto Internacional do Rio de Janeiro', 'Aeroporto Internacional', 'Brasil', -43.2437, -22.8091);


DELETE FROM AERONAVES WHERE AERONAVE_PREFIXO = 1;

UPDATE AERONAVES SET AERONAVE_CAPACIDADE = 200 WHERE AERONAVE_PREFIXO = 2;
UPDATE AERONAVES SET AERONAVE_FABRICANTE = 'Airbus' WHERE AERONAVE_PREFIXO = 3;

INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE, AERONAVE_EMPRESA)
VALUES (1, 'Boeing 737', 2015, 150, 'Boeing', 'Azul');
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE, AERONAVE_EMPRESA)
VALUES (2, 'Airbus A320', 2018, 180, 'Airbus', 'Gol');
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE, AERONAVE_EMPRESA)
VALUES (3, 'Embraer E195', 2020, 120, 'Embraer', 'LATAM');
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE, AERONAVE_EMPRESA)
VALUES (4, 'Boeing 777', 2017, 300, 'Boeing', 'American Airlines');
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE, AERONAVE_EMPRESA)
VALUES (5, 'Airbus A380', 2022, 500, 'Airbus', 'Emirates');


DELETE FROM FUNCIONARIOS WHERE FUNC_ID = 1;

UPDATE FUNCIONARIOS SET FUN_FUNCAO = 'Piloto' WHERE FUNC_ID = 2;
UPDATE FUNCIONARIOS SET FUNC_TELEFONE = '988888888' WHERE FUNC_ID = 3;

INSERT INTO FUNCIONARIOS (FUNC_ID, FUN_FUNCAO, FUNC_NOME, FUNC_DATANASC, FUNC_TELEFONE)
VALUES (1, 'Coordenador', 'Ana Costa', '1985-06-15', '999999999');
INSERT INTO FUNCIONARIOS (FUNC_ID, FUN_FUNCAO, FUNC_NOME, FUNC_DATANASC, FUNC_TELEFONE)
VALUES (2, 'Piloto', 'João Santos', '1980-11-23', '988888888');
INSERT INTO FUNCIONARIOS (FUNC_ID, FUN_FUNCAO, FUNC_NOME, FUNC_DATANASC, FUNC_TELEFONE)
VALUES (3, 'Comissário de Voo', 'Carlos Pereira', '1990-04-10', '977777777');
INSERT INTO FUNCIONARIOS (FUNC_ID, FUN_FUNCAO, FUNC_NOME, FUNC_DATANASC, FUNC_TELEFONE)
VALUES (4, 'Mecânico', 'Fernanda Lima', '1988-08-05', '966666666');
INSERT INTO FUNCIONARIOS (FUNC_ID, FUN_FUNCAO, FUNC_NOME, FUNC_DATANASC, FUNC_TELEFONE)
VALUES (5, 'Piloto', 'Pedro Oliveira', '1982-03-30', '955555555');


DELETE FROM RESERVA WHERE RESERVA_PASS = 987654321;

UPDATE RESERVA SET VOO_RESERVA_PASS = 102 WHERE RESERVA_PASS = 98765432100;
UPDATE RESERVA SET RESERVA_PASS = 11223344556 WHERE VOO_RESERVA_PASS = 104;

INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS) 
VALUES (123451500, 123);
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS) 
VALUES (987651201, 102);
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS)
VALUES (112231302, 103);
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS)
VALUES (223341403, 104);
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS) 
VALUES (345678901, 105);


DELETE FROM EQUIPES WHERE FUNC_EQUIPE = 2 AND VOO_EQUIPE = 101;

UPDATE EQUIPES SET FUNC_EQUIPE = 3 WHERE VOO_EQUIPE = 102;
UPDATE EQUIPES SET VOO_EQUIPE = 103 WHERE FUNC_EQUIPE = 4;

INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE)
VALUES (1, 123);
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE)
VALUES (2, 102);
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE)
VALUES (3, 103);
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE)
VALUES (4, 104);
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE)
VALUES (5, 105);