#CRIANDO BANCO DE DADOS
CREATE SCHEMA ESTUDO_CASO_5;

#SELECIONANDO BANCO DE DADOS
USE ESTUDO_CASO_5;

#CRIANDO TABELA CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(255),
    STATUS_PROGRAMA_FIDELIDADE ENUM('ATIVO', 'INATIVO')
);

#CRIANDO TABELA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(14) UNIQUE NOT NULL,
    CONTATO VARCHAR(100),
    ENDERECO VARCHAR(255)
);

#CRIANDO TABELA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50),
    PRECO DECIMAL(10, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    FORNECEDOR_ID INT,
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(ID)
);

#CRIANDO TABELA VENDAS
CREATE TABLE IF NOT EXISTS VENDAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA DATE NOT NULL,
    CLIENTE_ID INT,
    FORMA_PAGAMENTO ENUM('CARTÃO', 'DINHEIRO', 'TRANSFERÊNCIA') NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);

#CRIANDO TABELA ITENS_VENDIDOS
CREATE TABLE IF NOT EXISTS ITENS_VENDIDOS (
    VENDA_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (VENDA_ID, PRODUTO_ID),
    FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(ID)
);

#CRIANDO TABELA PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA DATE NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
    VENDA_ID INT,
    FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(ID)
);

#ALTER E DROP

#Exemplo: Adicionando uma coluna de EMAIL na tabela CLIENTES
ALTER TABLE CLIENTES ADD COLUMN EMAIL VARCHAR(100);

#Exemplo: Removendo a coluna CATEGORIA da tabela PRODUTOS
ALTER TABLE PRODUTOS DROP COLUMN CATEGORIA;

#Exemplo: Modificando o tipo de dados de CONTATO na tabela FORNECEDORES
ALTER TABLE FORNECEDORES MODIFY CONTATO VARCHAR(150);

#Exemplo: Excluindo a tabela ITENS_VENDIDOS
DROP TABLE IF EXISTS ITENS_VENDIDOS;

#Exemplo: Adicionando uma restrição UNIQUE em CNPJ na tabela FORNECEDORES
ALTER TABLE FORNECEDORES ADD CONSTRAINT UNIQUE (CNPJ);
