#CRIANDO O BANCO DE DADOS
CREATE SCHEMA ESTUDO_CASO_2;

#SELECIONANDO O BANCO DE DADOS
USE ESTUDO_CASO_2;

#CRIANDO TABELA PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

#CRIANDO TABELA AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS (
    CODIGO CHAR(3) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    PAIS VARCHAR(50) NOT NULL
);

#CRIANDO TABELA AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(50) NOT NULL,
    CAPACIDADE INT NOT NULL
);

#CRIANDO TABELA FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    FUNCAO ENUM('PILOTO', 'COMISSARIO', 'EQUIPE DE SOLO') NOT NULL,
    TELEFONE VARCHAR(15),
    CPF VARCHAR(11) UNIQUE NOT NULL
);

#CRIANDO TABELA VOOS
CREATE TABLE IF NOT EXISTS VOOS (
    CODIGO CHAR(6) PRIMARY KEY,
    ORIGEM CHAR(3),
    DESTINO CHAR(3),
    AERONAVE_ID INT,
    HORARIO_PARTIDA DATETIME NOT NULL,
    HORARIO_CHEGADA DATETIME NOT NULL,
    FOREIGN KEY (ORIGEM) REFERENCES AEROPORTOS(CODIGO),
    FOREIGN KEY (DESTINO) REFERENCES AEROPORTOS(CODIGO),
    FOREIGN KEY (AERONAVE_ID) REFERENCES AERONAVES(ID)
);

#CRIANDO TABELA OPERACOES_DE_VOO
CREATE TABLE IF NOT EXISTS OPERACOES_DE_VOO (
    VOO_CODIGO CHAR(6),
    FUNCIONARIO_ID INT,
    FUNCAO ENUM('PILOTO', 'COMISSARIO', 'EQUIPE DE SOLO') NOT NULL,
    PRIMARY KEY (VOO_CODIGO, FUNCIONARIO_ID),
    FOREIGN KEY (VOO_CODIGO) REFERENCES VOOS(CODIGO),
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(ID)
);

#CRIANDO TABELA RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PASSAGEIRO_ID INT NOT NULL,
    VOO_CODIGO CHAR(6) NOT NULL,
    DATA_RESERVA DATE NOT NULL,
    STATUS ENUM('CONFIRMADA', 'CANCELADA') NOT NULL,
    FOREIGN KEY (PASSAGEIRO_ID) REFERENCES PASSAGEIROS(ID),
    FOREIGN KEY (VOO_CODIGO) REFERENCES VOOS(CODIGO)
);

#CRIANDO TABELA EQUIPES
CREATE TABLE IF NOT EXISTS EQUIPES
(
FUNC_ID INT,
VOO_CODIGO INT,
PRIMARY KEY (FUNC_ID, VOO_CODIGO),
FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID),
FOREIGN KEY (VOO_CODIGO) REFERENCES VOOS(VOO_CODIGO)
);

#COMANDOS ALTER E DROP

#Exemplo: Adicionando coluna de EMAIL na tabela PASSAGEIROS
ALTER TABLE PASSAGEIROS ADD COLUMN EMAIL VARCHAR(100);

#Exemplo: Removendo a coluna TELEFONE da tabela FUNCIONARIOS
ALTER TABLE FUNCIONARIOS DROP COLUMN TELEFONE;

#Exemplo: Modificando o tipo de dados de NOME na tabela AEROPORTOS
ALTER TABLE AEROPORTOS MODIFY NOME VARCHAR(150);

#Exemplo: Excluindo a tabela OPERACOES_DE_VOO
DROP TABLE IF EXISTS OPERACOES_DE_VOO;

#Exemplo: Adicionando uma restrição UNIQUE em CPF na tabela FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT UNIQUE (CPF);
